name: Hud-Augment

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  augment-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@hud-augment')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@hud-augment')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@hud-augment')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@hud-augment'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Augment Assistant
        uses: code-hud/claude-code-action@feature/augment-cli-support
        with:
          augment_api_key: ${{ secrets.AUGMENT_API_KEY }}
          timeout_minutes: "60"
          allowed_bot_names: "hud-bot[bot]"
          github_token: ${{ github.actor == 'hud-bot[bot]' && secrets.GITHUB_TOKEN || '' }}
